# fly.toml app configuration file generated for academical on 2025-07-14T17:25:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'academical'
primary_region = 'nrt'

[build]

[processes]
    worker = "python main.py"

[[machines]]
    auto_stop_machines = false
    auto_start_machines = true
    min_machines_running = 1

[services]
